name: Test Flaky

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Checkout version
        run: git checkout cc2babc1f75c93bf89a8f10da525f944c15d02ea

      - name: Compile the project
        run: mvn test-compile -pl hadoop-tools/hadoop-distcp -am -Drat.skip
  
      - name: Run tests
        run: mvn -pl hadoop-tools/hadoop-distcp test -Dtest=org.apache.hadoop.tools.util.TestThrottledInputStream#testRead
        
      # - name: Set up JDK 8 for NonDex
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'adopt'
      #     java-version: '8'
  
      - name: Run NonDex to check for flaky tests
        run: mvn -pl hadoop-tools/hadoop-distcp edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.apache.hadoop.tools.util.TestThrottledInputStream#testRead -DnondexRuns=20
